// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+3,0,"Instruction_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"Instr_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+5,0,"DM_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"DM_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"DM_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"DM_Mask_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+9,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("Pip_RV32I", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+10,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"Instruction_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"Instr_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"DM_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+15,0,"DM_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+16,0,"DM_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"DM_Mask_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+18,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"PC_F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+20,0,"PC_Plus4_F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,0,"Instruction_F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+22,0,"PC_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+23,0,"PC_Plus4_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+24,0,"Instruction_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+25,0,"Opcode_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+26,0,"Func3_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+27,0,"Func7_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+28,0,"Src_Addr1_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+29,0,"Src_Addr2_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+30,0,"Des_Addr_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+31,0,"Immediate_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 24,0);
    tracep->declBus(c+32,0,"Imm_Ext_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+33,0,"Reg_WrEn_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+34,0,"Result_Src_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+35,0,"Imm_Type_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+36,0,"Iadder_Src_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+37,0,"ALU_Src_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+38,0,"ALU_Control_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+39,0,"DM_WrEn_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"Branch_Cond_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+41,0,"Load_Unsigned_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+42,0,"Load_Size_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+43,0,"PC_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"PC_Plus4_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"Func3_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+46,0,"Reg_WrEn_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+47,0,"Result_Src_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+48,0,"Iadder_Src_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"ALU_Src_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+50,0,"ALU_Control_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+51,0,"DM_WrEn_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+52,0,"Branch_Cond_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+53,0,"Load_Unsigned_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+54,0,"Load_Size_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+55,0,"Read_Data1_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"Read_Data2_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+57,0,"Imm_Ext_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+58,0,"ALU_Result_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+59,0,"Imm_Added_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+60,0,"Des_Addr_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+61,0,"Branch_Taken_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+62,0,"PC_Plus4_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+63,0,"ALU_Result_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"Read_Data2_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+65,0,"Reg_WrEn_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+66,0,"Func3_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+67,0,"Result_Src_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+68,0,"Load_Size_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+69,0,"Load_Unsigned_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"Loaded_Data_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+71,0,"DM_WrData_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+72,0,"DM_Addr_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+73,0,"DM_Wr_Req_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+74,0,"DM_Mask_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+75,0,"DM_WrEn_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"Imm_Ext_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+77,0,"Imm_Added_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+78,0,"Des_Addr_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+79,0,"Data_M",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+80,0,"PC_Plus4_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+81,0,"ALU_Result_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+82,0,"Loaded_Data_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"Imm_Ext_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"Imm_Added_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+85,0,"Result_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+86,0,"Reg_WrEn_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+87,0,"Result_Src_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+88,0,"Des_Addr_W",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+89,0,"Stall_F",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"Stall_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+91,0,"Flush_D",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+92,0,"Flush_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+93,0,"ForwardA_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+94,0,"ForwardB_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+95,0,"Src_Addr1_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+96,0,"Src_Addr2_E",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+97,0,"ForwardA_Data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"ForwardB_Data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+99,0,"SrcA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"SrcB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("Imm_Adder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+101,0,"Iadder_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+102,0,"PC_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"Src_Data1_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,0,"Imm_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"Added_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+106,0,"temp_adder_src",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("alu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+107,0,"Src1_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+108,0,"Src2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+109,0,"ALU_Control_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+110,0,"ALU_Result_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+111,0,"signed_src1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+112,0,"signed_src2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("branch_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+113,0,"Src_Data1_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+114,0,"Src_Data2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+115,0,"bgeu_bltu_bge_blt_bne_beq_jalr_jal",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+116,0,"Branch_Taken_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"equal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"not_equal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"less_than",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"greater_equal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"less_than_unsigned",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"greater_equal_unsigned",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("decoder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+123,0,"Opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+124,0,"Func3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+125,0,"Func7",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"Reg_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+127,0,"Imm_Type_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+128,0,"Iadder_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"ALU_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+130,0,"ALU_Control_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+131,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+132,0,"bgeu_bltu_bge_blt_bne_beq_jalr_jal",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+133,0,"Load_Unsigned_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+134,0,"Load_Size_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+135,0,"Result_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->popPrefix();
    tracep->pushPrefix("hazard_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+136,0,"Src_Addr1_D_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+137,0,"Src_Addr2_D_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+138,0,"Des_Addr_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+139,0,"Reg_WrEn_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+140,0,"Result_Src_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+141,0,"Src_Addr1_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+142,0,"Src_Addr2_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+143,0,"Des_Addr_M_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+144,0,"Reg_WrEn_M_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+145,0,"Des_Addr_W_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+146,0,"Reg_WrEn_W_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"Branch_Taken_E_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"Stall_F_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"Stall_D_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"Flush_D_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"Flush_E_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+152,0,"ForwardA_E_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+153,0,"ForwardB_E_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+154,0,"load_use_hazard",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"control_hazard",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("imm_extend", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+156,0,"Instr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,7);
    tracep->declBus(c+157,0,"Imm_Type_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+158,0,"Imm_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("load_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+159,0,"Read_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+160,0,"iadder_out_1to0_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+161,0,"Load_Size_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+162,0,"Load_Unsigned_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+163,0,"Loaded_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("pc_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+164,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"Stall_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"Branch_Taken_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+168,0,"Target_PC_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+169,0,"PC_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+170,0,"PC_Plus4_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+171,0,"Temp_PC_Out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_d_e", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+172,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"Flush_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"Reg_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"Result_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+177,0,"DM_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"Iadder_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+179,0,"Load_Size_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+180,0,"Load_Unsigned_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+181,0,"ALU_Control_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+182,0,"ALU_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+183,0,"PC_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+184,0,"Func3_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+185,0,"Branch_Cond_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+186,0,"Imm_Ext_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+187,0,"PC_Plus4_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+188,0,"Des_Addr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+189,0,"Src_Addr1_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+190,0,"Src_Addr2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+191,0,"Src_Addr1_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+192,0,"Src_Addr2_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+193,0,"Des_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+194,0,"Reg_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+195,0,"Result_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+196,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"Iadder_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"Load_Size_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+199,0,"Load_Unsigned_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+200,0,"ALU_Control_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+201,0,"ALU_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+202,0,"PC_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"Func3_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+204,0,"Branch_Cond_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+205,0,"Imm_Ext_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,0,"PC_Plus4_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_e_m", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+207,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+209,0,"Reg_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+210,0,"Result_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+211,0,"Load_Size_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+212,0,"Load_Unsigned_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+213,0,"DM_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+214,0,"Func3_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+215,0,"ALU_Result_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+216,0,"Read_Data2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+217,0,"Added_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+218,0,"PC_Plus4_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+219,0,"Imm_Ext_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+220,0,"Des_Addr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+221,0,"Des_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+222,0,"Imm_Ext_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+223,0,"Reg_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+224,0,"Result_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+225,0,"Load_Size_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+226,0,"Load_Unsigned_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+227,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+228,0,"Func3_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+229,0,"ALU_Result_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+230,0,"Read_Data2_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+231,0,"Added_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+232,0,"PC_Plus4_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_f_d", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+233,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"Stall_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+236,0,"Flush_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+237,0,"Instr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+238,0,"PC_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+239,0,"PC_Plus4_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+240,0,"Instr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+241,0,"PC_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+242,0,"PC_Plus4_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_file", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+243,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+244,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+246,0,"Src_Addr1_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+247,0,"Src_Addr2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+248,0,"Des_Addr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+249,0,"Des_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+250,0,"Src_Data1_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+251,0,"Src_Data2_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+252,0,"Temp_Src_Data1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+253,0,"Temp_Src_Data2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("register", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+254+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+286,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_m_w", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+287,0,"Clk_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+288,0,"Rst_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+289,0,"Reg_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+290,0,"Result_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+291,0,"ALU_Result_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+292,0,"Loaded_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+293,0,"Added_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+294,0,"PC_Plus4_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+295,0,"Imm_Ext_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+296,0,"Des_Addr_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+297,0,"Des_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+298,0,"Imm_Ext_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+299,0,"Reg_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+300,0,"Result_Src_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+301,0,"ALU_Result_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+302,0,"Loaded_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+303,0,"Added_Data_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+304,0,"PC_Plus4_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("store_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+305,0,"DM_WrEn_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+306,0,"Func3_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+307,0,"Added_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+308,0,"Src_Data2_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+309,0,"DM_WrMask_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+310,0,"DM_WrData_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+311,0,"DM_Addr_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+312,0,"DM_WrEn_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("wb_unit", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+313,0,"Result_Src_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+314,0,"Imm_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+315,0,"ALU_Result_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+316,0,"Loaded_Data_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+317,0,"Imm_Added_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+318,0,"PC_Plus4_In",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+319,0,"Result_Out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.Clk_In));
    bufp->fullBit(oldp+2,(vlSelfRef.Rst_In));
    bufp->fullIData(oldp+3,(vlSelfRef.Instruction_In),32);
    bufp->fullIData(oldp+4,(vlSelfRef.Instr_Addr_Out),32);
    bufp->fullIData(oldp+5,(vlSelfRef.DM_Data_In),32);
    bufp->fullIData(oldp+6,(vlSelfRef.DM_Addr_Out),32);
    bufp->fullIData(oldp+7,(vlSelfRef.DM_Data_Out),32);
    bufp->fullCData(oldp+8,(vlSelfRef.DM_Mask_Out),4);
    bufp->fullBit(oldp+9,(vlSelfRef.DM_WrEn_Out));
    bufp->fullBit(oldp+10,(vlSelfRef.Pip_RV32I__DOT__Clk_In));
    bufp->fullBit(oldp+11,(vlSelfRef.Pip_RV32I__DOT__Rst_In));
    bufp->fullIData(oldp+12,(vlSelfRef.Pip_RV32I__DOT__Instruction_In),32);
    bufp->fullIData(oldp+13,(vlSelfRef.Pip_RV32I__DOT__Instr_Addr_Out),32);
    bufp->fullIData(oldp+14,(vlSelfRef.Pip_RV32I__DOT__DM_Data_In),32);
    bufp->fullIData(oldp+15,(vlSelfRef.Pip_RV32I__DOT__DM_Addr_Out),32);
    bufp->fullIData(oldp+16,(vlSelfRef.Pip_RV32I__DOT__DM_Data_Out),32);
    bufp->fullCData(oldp+17,(vlSelfRef.Pip_RV32I__DOT__DM_Mask_Out),4);
    bufp->fullBit(oldp+18,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_Out));
    bufp->fullIData(oldp+19,(vlSelfRef.Pip_RV32I__DOT__PC_F),32);
    bufp->fullIData(oldp+20,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_F),32);
    bufp->fullIData(oldp+21,(vlSelfRef.Pip_RV32I__DOT__Instruction_F),32);
    bufp->fullIData(oldp+22,(vlSelfRef.Pip_RV32I__DOT__PC_D),32);
    bufp->fullIData(oldp+23,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_D),32);
    bufp->fullIData(oldp+24,(vlSelfRef.Pip_RV32I__DOT__Instruction_D),32);
    bufp->fullCData(oldp+25,(vlSelfRef.Pip_RV32I__DOT__Opcode_D),7);
    bufp->fullCData(oldp+26,(vlSelfRef.Pip_RV32I__DOT__Func3_D),3);
    bufp->fullBit(oldp+27,(vlSelfRef.Pip_RV32I__DOT__Func7_D));
    bufp->fullCData(oldp+28,(vlSelfRef.Pip_RV32I__DOT__Src_Addr1_D),5);
    bufp->fullCData(oldp+29,(vlSelfRef.Pip_RV32I__DOT__Src_Addr2_D),5);
    bufp->fullCData(oldp+30,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_D),5);
    bufp->fullIData(oldp+31,(vlSelfRef.Pip_RV32I__DOT__Immediate_D),25);
    bufp->fullIData(oldp+32,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_D),32);
    bufp->fullBit(oldp+33,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_D));
    bufp->fullCData(oldp+34,(vlSelfRef.Pip_RV32I__DOT__Result_Src_D),3);
    bufp->fullCData(oldp+35,(vlSelfRef.Pip_RV32I__DOT__Imm_Type_D),3);
    bufp->fullBit(oldp+36,(vlSelfRef.Pip_RV32I__DOT__Iadder_Src_D));
    bufp->fullBit(oldp+37,(vlSelfRef.Pip_RV32I__DOT__ALU_Src_D));
    bufp->fullCData(oldp+38,(vlSelfRef.Pip_RV32I__DOT__ALU_Control_D),4);
    bufp->fullBit(oldp+39,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_D));
    bufp->fullCData(oldp+40,(vlSelfRef.Pip_RV32I__DOT__Branch_Cond_D),8);
    bufp->fullBit(oldp+41,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_D));
    bufp->fullCData(oldp+42,(vlSelfRef.Pip_RV32I__DOT__Load_Size_D),2);
    bufp->fullIData(oldp+43,(vlSelfRef.Pip_RV32I__DOT__PC_E),32);
    bufp->fullIData(oldp+44,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_E),32);
    bufp->fullCData(oldp+45,(vlSelfRef.Pip_RV32I__DOT__Func3_E),2);
    bufp->fullBit(oldp+46,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_E));
    bufp->fullCData(oldp+47,(vlSelfRef.Pip_RV32I__DOT__Result_Src_E),3);
    bufp->fullBit(oldp+48,(vlSelfRef.Pip_RV32I__DOT__Iadder_Src_E));
    bufp->fullBit(oldp+49,(vlSelfRef.Pip_RV32I__DOT__ALU_Src_E));
    bufp->fullCData(oldp+50,(vlSelfRef.Pip_RV32I__DOT__ALU_Control_E),4);
    bufp->fullBit(oldp+51,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_E));
    bufp->fullCData(oldp+52,(vlSelfRef.Pip_RV32I__DOT__Branch_Cond_E),8);
    bufp->fullBit(oldp+53,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_E));
    bufp->fullCData(oldp+54,(vlSelfRef.Pip_RV32I__DOT__Load_Size_E),2);
    bufp->fullIData(oldp+55,(vlSelfRef.Pip_RV32I__DOT__Read_Data1_E),32);
    bufp->fullIData(oldp+56,(vlSelfRef.Pip_RV32I__DOT__Read_Data2_E),32);
    bufp->fullIData(oldp+57,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_E),32);
    bufp->fullIData(oldp+58,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_E),32);
    bufp->fullIData(oldp+59,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_E),32);
    bufp->fullCData(oldp+60,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_E),5);
    bufp->fullBit(oldp+61,(vlSelfRef.Pip_RV32I__DOT__Branch_Taken_E));
    bufp->fullIData(oldp+62,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_M),32);
    bufp->fullIData(oldp+63,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_M),32);
    bufp->fullIData(oldp+64,(vlSelfRef.Pip_RV32I__DOT__Read_Data2_M),32);
    bufp->fullBit(oldp+65,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_M));
    bufp->fullCData(oldp+66,(vlSelfRef.Pip_RV32I__DOT__Func3_M),2);
    bufp->fullCData(oldp+67,(vlSelfRef.Pip_RV32I__DOT__Result_Src_M),3);
    bufp->fullCData(oldp+68,(vlSelfRef.Pip_RV32I__DOT__Load_Size_M),2);
    bufp->fullBit(oldp+69,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_M));
    bufp->fullIData(oldp+70,(vlSelfRef.Pip_RV32I__DOT__Loaded_Data_M),32);
    bufp->fullIData(oldp+71,(vlSelfRef.Pip_RV32I__DOT__DM_WrData_M),32);
    bufp->fullIData(oldp+72,(vlSelfRef.Pip_RV32I__DOT__DM_Addr_M),32);
    bufp->fullBit(oldp+73,(vlSelfRef.Pip_RV32I__DOT__DM_Wr_Req_M));
    bufp->fullCData(oldp+74,(vlSelfRef.Pip_RV32I__DOT__DM_Mask_M),4);
    bufp->fullBit(oldp+75,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_M));
    bufp->fullIData(oldp+76,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_M),32);
    bufp->fullIData(oldp+77,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_M),32);
    bufp->fullCData(oldp+78,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_M),5);
    bufp->fullIData(oldp+79,(vlSelfRef.Pip_RV32I__DOT__Data_M),32);
    bufp->fullIData(oldp+80,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_W),32);
    bufp->fullIData(oldp+81,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_W),32);
    bufp->fullIData(oldp+82,(vlSelfRef.Pip_RV32I__DOT__Loaded_Data_W),32);
    bufp->fullIData(oldp+83,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_W),32);
    bufp->fullIData(oldp+84,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_W),32);
    bufp->fullIData(oldp+85,(vlSelfRef.Pip_RV32I__DOT__Result_W),32);
    bufp->fullBit(oldp+86,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_W));
    bufp->fullCData(oldp+87,(vlSelfRef.Pip_RV32I__DOT__Result_Src_W),3);
    bufp->fullCData(oldp+88,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_W),5);
    bufp->fullBit(oldp+89,(vlSelfRef.Pip_RV32I__DOT__Stall_F));
    bufp->fullBit(oldp+90,(vlSelfRef.Pip_RV32I__DOT__Stall_D));
    bufp->fullBit(oldp+91,(vlSelfRef.Pip_RV32I__DOT__Flush_D));
    bufp->fullBit(oldp+92,(vlSelfRef.Pip_RV32I__DOT__Flush_E));
    bufp->fullCData(oldp+93,(vlSelfRef.Pip_RV32I__DOT__ForwardA_E),2);
    bufp->fullCData(oldp+94,(vlSelfRef.Pip_RV32I__DOT__ForwardB_E),2);
    bufp->fullCData(oldp+95,(vlSelfRef.Pip_RV32I__DOT__Src_Addr1_E),5);
    bufp->fullCData(oldp+96,(vlSelfRef.Pip_RV32I__DOT__Src_Addr2_E),5);
    bufp->fullIData(oldp+97,(vlSelfRef.Pip_RV32I__DOT__ForwardA_Data),32);
    bufp->fullIData(oldp+98,(vlSelfRef.Pip_RV32I__DOT__ForwardB_Data),32);
    bufp->fullIData(oldp+99,(vlSelfRef.Pip_RV32I__DOT__SrcA),32);
    bufp->fullIData(oldp+100,(vlSelfRef.Pip_RV32I__DOT__SrcB),32);
    bufp->fullBit(oldp+101,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Iadder_Src_In));
    bufp->fullIData(oldp+102,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__PC_In),32);
    bufp->fullIData(oldp+103,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Src_Data1_In),32);
    bufp->fullIData(oldp+104,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Imm_Data_In),32);
    bufp->fullIData(oldp+105,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Added_Data_Out),32);
    bufp->fullIData(oldp+106,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__temp_adder_src),32);
    bufp->fullIData(oldp+107,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__Src1_In),32);
    bufp->fullIData(oldp+108,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__Src2_In),32);
    bufp->fullCData(oldp+109,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__ALU_Control_In),4);
    bufp->fullIData(oldp+110,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__ALU_Result_Out),32);
    bufp->fullIData(oldp+111,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__signed_src1),32);
    bufp->fullIData(oldp+112,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__signed_src2),32);
    bufp->fullIData(oldp+113,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Src_Data1_In),32);
    bufp->fullIData(oldp+114,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Src_Data2_In),32);
    bufp->fullCData(oldp+115,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal),8);
    bufp->fullBit(oldp+116,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Branch_Taken_Out));
    bufp->fullBit(oldp+117,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__equal));
    bufp->fullBit(oldp+118,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__not_equal));
    bufp->fullBit(oldp+119,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__less_than));
    bufp->fullBit(oldp+120,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__greater_equal));
    bufp->fullBit(oldp+121,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__less_than_unsigned));
    bufp->fullBit(oldp+122,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__greater_equal_unsigned));
    bufp->fullCData(oldp+123,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Opcode),7);
    bufp->fullCData(oldp+124,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Func3),3);
    bufp->fullBit(oldp+125,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Func7));
    bufp->fullBit(oldp+126,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Reg_WrEn_Out));
    bufp->fullCData(oldp+127,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Imm_Type_Out),3);
    bufp->fullBit(oldp+128,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Iadder_Src_Out));
    bufp->fullBit(oldp+129,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__ALU_Src_Out));
    bufp->fullCData(oldp+130,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__ALU_Control_Out),4);
    bufp->fullBit(oldp+131,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__DM_WrEn_Out));
    bufp->fullCData(oldp+132,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal),8);
    bufp->fullBit(oldp+133,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Load_Unsigned_Out));
    bufp->fullCData(oldp+134,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Load_Size_Out),2);
    bufp->fullCData(oldp+135,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Result_Src_Out),3);
    bufp->fullCData(oldp+136,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_D_In),5);
    bufp->fullCData(oldp+137,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_D_In),5);
    bufp->fullCData(oldp+138,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_E_In),5);
    bufp->fullBit(oldp+139,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_E_In));
    bufp->fullCData(oldp+140,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Result_Src_E_In),3);
    bufp->fullCData(oldp+141,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_E_In),5);
    bufp->fullCData(oldp+142,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_E_In),5);
    bufp->fullCData(oldp+143,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_M_In),5);
    bufp->fullBit(oldp+144,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_M_In));
    bufp->fullCData(oldp+145,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_W_In),5);
    bufp->fullBit(oldp+146,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_W_In));
    bufp->fullBit(oldp+147,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Branch_Taken_E_In));
    bufp->fullBit(oldp+148,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Stall_F_Out));
    bufp->fullBit(oldp+149,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Stall_D_Out));
    bufp->fullBit(oldp+150,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Flush_D_Out));
    bufp->fullBit(oldp+151,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Flush_E_Out));
    bufp->fullCData(oldp+152,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__ForwardA_E_Out),2);
    bufp->fullCData(oldp+153,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__ForwardB_E_Out),2);
    bufp->fullBit(oldp+154,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__load_use_hazard));
    bufp->fullBit(oldp+155,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__control_hazard));
    bufp->fullIData(oldp+156,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Instr_In),25);
    bufp->fullCData(oldp+157,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Imm_Type_In),3);
    bufp->fullIData(oldp+158,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Imm_Out),32);
    bufp->fullIData(oldp+159,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Read_Data_In),32);
    bufp->fullCData(oldp+160,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__iadder_out_1to0_in),2);
    bufp->fullCData(oldp+161,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Load_Size_In),2);
    bufp->fullBit(oldp+162,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Load_Unsigned_In));
    bufp->fullIData(oldp+163,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Loaded_Data_Out),32);
    bufp->fullBit(oldp+164,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Clk_In));
    bufp->fullBit(oldp+165,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Rst_In));
    bufp->fullBit(oldp+166,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Stall_In));
    bufp->fullBit(oldp+167,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Branch_Taken_In));
    bufp->fullIData(oldp+168,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Target_PC_In),32);
    bufp->fullIData(oldp+169,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__PC_Out),32);
    bufp->fullIData(oldp+170,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__PC_Plus4_Out),32);
    bufp->fullIData(oldp+171,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Temp_PC_Out),32);
    bufp->fullBit(oldp+172,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Clk_In));
    bufp->fullBit(oldp+173,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Rst_In));
    bufp->fullBit(oldp+174,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Flush_In));
    bufp->fullBit(oldp+175,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_In));
    bufp->fullCData(oldp+176,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_In),3);
    bufp->fullBit(oldp+177,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_In));
    bufp->fullBit(oldp+178,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_In));
    bufp->fullCData(oldp+179,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_In),2);
    bufp->fullBit(oldp+180,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_In));
    bufp->fullCData(oldp+181,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_In),4);
    bufp->fullBit(oldp+182,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_In));
    bufp->fullIData(oldp+183,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_In),32);
    bufp->fullCData(oldp+184,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Func3_In),2);
    bufp->fullCData(oldp+185,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_In),8);
    bufp->fullIData(oldp+186,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_In),32);
    bufp->fullIData(oldp+187,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_In),32);
    bufp->fullCData(oldp+188,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_In),5);
    bufp->fullCData(oldp+189,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_In),5);
    bufp->fullCData(oldp+190,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_In),5);
    bufp->fullCData(oldp+191,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_Out),5);
    bufp->fullCData(oldp+192,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_Out),5);
    bufp->fullCData(oldp+193,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_Out),5);
    bufp->fullBit(oldp+194,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_Out));
    bufp->fullCData(oldp+195,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_Out),3);
    bufp->fullBit(oldp+196,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_Out));
    bufp->fullBit(oldp+197,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_Out));
    bufp->fullCData(oldp+198,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_Out),2);
    bufp->fullBit(oldp+199,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_Out));
    bufp->fullCData(oldp+200,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_Out),4);
    bufp->fullBit(oldp+201,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_Out));
    bufp->fullIData(oldp+202,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Out),32);
    bufp->fullCData(oldp+203,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Func3_Out),2);
    bufp->fullCData(oldp+204,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_Out),8);
    bufp->fullIData(oldp+205,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_Out),32);
    bufp->fullIData(oldp+206,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_Out),32);
    bufp->fullBit(oldp+207,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Clk_In));
    bufp->fullBit(oldp+208,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Rst_In));
    bufp->fullBit(oldp+209,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_In));
    bufp->fullCData(oldp+210,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_In),3);
    bufp->fullCData(oldp+211,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_In),2);
    bufp->fullBit(oldp+212,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_In));
    bufp->fullBit(oldp+213,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_In));
    bufp->fullCData(oldp+214,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Func3_In),2);
    bufp->fullIData(oldp+215,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_In),32);
    bufp->fullIData(oldp+216,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_In),32);
    bufp->fullIData(oldp+217,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_In),32);
    bufp->fullIData(oldp+218,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_In),32);
    bufp->fullIData(oldp+219,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_In),32);
    bufp->fullCData(oldp+220,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_In),5);
    bufp->fullCData(oldp+221,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_Out),5);
    bufp->fullIData(oldp+222,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_Out),32);
    bufp->fullBit(oldp+223,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_Out));
    bufp->fullCData(oldp+224,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_Out),3);
    bufp->fullCData(oldp+225,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_Out),2);
    bufp->fullBit(oldp+226,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_Out));
    bufp->fullBit(oldp+227,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_Out));
    bufp->fullCData(oldp+228,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Func3_Out),2);
    bufp->fullIData(oldp+229,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_Out),32);
    bufp->fullIData(oldp+230,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_Out),32);
    bufp->fullIData(oldp+231,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_Out),32);
    bufp->fullIData(oldp+232,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_Out),32);
    bufp->fullBit(oldp+233,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Clk_In));
    bufp->fullBit(oldp+234,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Rst_In));
    bufp->fullBit(oldp+235,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Stall_In));
    bufp->fullBit(oldp+236,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Flush_In));
    bufp->fullIData(oldp+237,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Instr_In),32);
    bufp->fullIData(oldp+238,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_In),32);
    bufp->fullIData(oldp+239,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_In),32);
    bufp->fullIData(oldp+240,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Instr_Out),32);
    bufp->fullIData(oldp+241,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Out),32);
    bufp->fullIData(oldp+242,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_Out),32);
    bufp->fullBit(oldp+243,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Clk_In));
    bufp->fullBit(oldp+244,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Rst_In));
    bufp->fullBit(oldp+245,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__WrEn_In));
    bufp->fullCData(oldp+246,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Addr1_In),5);
    bufp->fullCData(oldp+247,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Addr2_In),5);
    bufp->fullCData(oldp+248,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Des_Addr_In),5);
    bufp->fullIData(oldp+249,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Des_Data_In),32);
    bufp->fullIData(oldp+250,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Data1_Out),32);
    bufp->fullIData(oldp+251,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Data2_Out),32);
    bufp->fullIData(oldp+252,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data1),32);
    bufp->fullIData(oldp+253,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data2),32);
    bufp->fullIData(oldp+254,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[0]),32);
    bufp->fullIData(oldp+255,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[1]),32);
    bufp->fullIData(oldp+256,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[2]),32);
    bufp->fullIData(oldp+257,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[3]),32);
    bufp->fullIData(oldp+258,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[4]),32);
    bufp->fullIData(oldp+259,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[5]),32);
    bufp->fullIData(oldp+260,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[6]),32);
    bufp->fullIData(oldp+261,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[7]),32);
    bufp->fullIData(oldp+262,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[8]),32);
    bufp->fullIData(oldp+263,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[9]),32);
    bufp->fullIData(oldp+264,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[10]),32);
    bufp->fullIData(oldp+265,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[11]),32);
    bufp->fullIData(oldp+266,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[12]),32);
    bufp->fullIData(oldp+267,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[13]),32);
    bufp->fullIData(oldp+268,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[14]),32);
    bufp->fullIData(oldp+269,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[15]),32);
    bufp->fullIData(oldp+270,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[16]),32);
    bufp->fullIData(oldp+271,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[17]),32);
    bufp->fullIData(oldp+272,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[18]),32);
    bufp->fullIData(oldp+273,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[19]),32);
    bufp->fullIData(oldp+274,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[20]),32);
    bufp->fullIData(oldp+275,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[21]),32);
    bufp->fullIData(oldp+276,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[22]),32);
    bufp->fullIData(oldp+277,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[23]),32);
    bufp->fullIData(oldp+278,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[24]),32);
    bufp->fullIData(oldp+279,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[25]),32);
    bufp->fullIData(oldp+280,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[26]),32);
    bufp->fullIData(oldp+281,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[27]),32);
    bufp->fullIData(oldp+282,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[28]),32);
    bufp->fullIData(oldp+283,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[29]),32);
    bufp->fullIData(oldp+284,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[30]),32);
    bufp->fullIData(oldp+285,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[31]),32);
    bufp->fullIData(oldp+286,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__i),32);
    bufp->fullBit(oldp+287,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Clk_In));
    bufp->fullBit(oldp+288,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Rst_In));
    bufp->fullBit(oldp+289,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_In));
    bufp->fullCData(oldp+290,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_In),3);
    bufp->fullIData(oldp+291,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_In),32);
    bufp->fullIData(oldp+292,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_In),32);
    bufp->fullIData(oldp+293,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_In),32);
    bufp->fullIData(oldp+294,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_In),32);
    bufp->fullIData(oldp+295,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_In),32);
    bufp->fullCData(oldp+296,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_In),5);
    bufp->fullCData(oldp+297,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_Out),5);
    bufp->fullIData(oldp+298,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_Out),32);
    bufp->fullBit(oldp+299,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_Out));
    bufp->fullCData(oldp+300,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_Out),3);
    bufp->fullIData(oldp+301,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_Out),32);
    bufp->fullIData(oldp+302,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_Out),32);
    bufp->fullIData(oldp+303,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_Out),32);
    bufp->fullIData(oldp+304,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_Out),32);
    bufp->fullBit(oldp+305,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_In));
    bufp->fullCData(oldp+306,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Func3_In),2);
    bufp->fullIData(oldp+307,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Added_Data_In),32);
    bufp->fullIData(oldp+308,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Src_Data2_In),32);
    bufp->fullCData(oldp+309,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrMask_Out),4);
    bufp->fullIData(oldp+310,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrData_Out),32);
    bufp->fullIData(oldp+311,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_Addr_Out),32);
    bufp->fullBit(oldp+312,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_Out));
    bufp->fullCData(oldp+313,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Result_Src_In),3);
    bufp->fullIData(oldp+314,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Imm_Data_In),32);
    bufp->fullIData(oldp+315,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__ALU_Result_In),32);
    bufp->fullIData(oldp+316,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Loaded_Data_In),32);
    bufp->fullIData(oldp+317,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Imm_Added_In),32);
    bufp->fullIData(oldp+318,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__PC_Plus4_In),32);
    bufp->fullIData(oldp+319,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Result_Out),32);
}
