// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelfRef.Clk_In));
    bufp->chgBit(oldp+1,(vlSelfRef.Rst_In));
    bufp->chgIData(oldp+2,(vlSelfRef.Instruction_In),32);
    bufp->chgIData(oldp+3,(vlSelfRef.Instr_Addr_Out),32);
    bufp->chgIData(oldp+4,(vlSelfRef.DM_Data_In),32);
    bufp->chgIData(oldp+5,(vlSelfRef.DM_Addr_Out),32);
    bufp->chgIData(oldp+6,(vlSelfRef.DM_Data_Out),32);
    bufp->chgCData(oldp+7,(vlSelfRef.DM_Mask_Out),4);
    bufp->chgBit(oldp+8,(vlSelfRef.DM_WrEn_Out));
    bufp->chgBit(oldp+9,(vlSelfRef.Pip_RV32I__DOT__Clk_In));
    bufp->chgBit(oldp+10,(vlSelfRef.Pip_RV32I__DOT__Rst_In));
    bufp->chgIData(oldp+11,(vlSelfRef.Pip_RV32I__DOT__Instruction_In),32);
    bufp->chgIData(oldp+12,(vlSelfRef.Pip_RV32I__DOT__Instr_Addr_Out),32);
    bufp->chgIData(oldp+13,(vlSelfRef.Pip_RV32I__DOT__DM_Data_In),32);
    bufp->chgIData(oldp+14,(vlSelfRef.Pip_RV32I__DOT__DM_Addr_Out),32);
    bufp->chgIData(oldp+15,(vlSelfRef.Pip_RV32I__DOT__DM_Data_Out),32);
    bufp->chgCData(oldp+16,(vlSelfRef.Pip_RV32I__DOT__DM_Mask_Out),4);
    bufp->chgBit(oldp+17,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_Out));
    bufp->chgIData(oldp+18,(vlSelfRef.Pip_RV32I__DOT__PC_F),32);
    bufp->chgIData(oldp+19,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_F),32);
    bufp->chgIData(oldp+20,(vlSelfRef.Pip_RV32I__DOT__Instruction_F),32);
    bufp->chgIData(oldp+21,(vlSelfRef.Pip_RV32I__DOT__PC_D),32);
    bufp->chgIData(oldp+22,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_D),32);
    bufp->chgIData(oldp+23,(vlSelfRef.Pip_RV32I__DOT__Instruction_D),32);
    bufp->chgCData(oldp+24,(vlSelfRef.Pip_RV32I__DOT__Opcode_D),7);
    bufp->chgCData(oldp+25,(vlSelfRef.Pip_RV32I__DOT__Func3_D),3);
    bufp->chgBit(oldp+26,(vlSelfRef.Pip_RV32I__DOT__Func7_D));
    bufp->chgCData(oldp+27,(vlSelfRef.Pip_RV32I__DOT__Src_Addr1_D),5);
    bufp->chgCData(oldp+28,(vlSelfRef.Pip_RV32I__DOT__Src_Addr2_D),5);
    bufp->chgCData(oldp+29,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_D),5);
    bufp->chgIData(oldp+30,(vlSelfRef.Pip_RV32I__DOT__Immediate_D),25);
    bufp->chgIData(oldp+31,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_D),32);
    bufp->chgBit(oldp+32,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_D));
    bufp->chgCData(oldp+33,(vlSelfRef.Pip_RV32I__DOT__Result_Src_D),3);
    bufp->chgCData(oldp+34,(vlSelfRef.Pip_RV32I__DOT__Imm_Type_D),3);
    bufp->chgBit(oldp+35,(vlSelfRef.Pip_RV32I__DOT__Iadder_Src_D));
    bufp->chgBit(oldp+36,(vlSelfRef.Pip_RV32I__DOT__ALU_Src_D));
    bufp->chgCData(oldp+37,(vlSelfRef.Pip_RV32I__DOT__ALU_Control_D),4);
    bufp->chgBit(oldp+38,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_D));
    bufp->chgCData(oldp+39,(vlSelfRef.Pip_RV32I__DOT__Branch_Cond_D),8);
    bufp->chgBit(oldp+40,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_D));
    bufp->chgCData(oldp+41,(vlSelfRef.Pip_RV32I__DOT__Load_Size_D),2);
    bufp->chgIData(oldp+42,(vlSelfRef.Pip_RV32I__DOT__PC_E),32);
    bufp->chgIData(oldp+43,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_E),32);
    bufp->chgCData(oldp+44,(vlSelfRef.Pip_RV32I__DOT__Func3_E),2);
    bufp->chgBit(oldp+45,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_E));
    bufp->chgCData(oldp+46,(vlSelfRef.Pip_RV32I__DOT__Result_Src_E),3);
    bufp->chgBit(oldp+47,(vlSelfRef.Pip_RV32I__DOT__Iadder_Src_E));
    bufp->chgBit(oldp+48,(vlSelfRef.Pip_RV32I__DOT__ALU_Src_E));
    bufp->chgCData(oldp+49,(vlSelfRef.Pip_RV32I__DOT__ALU_Control_E),4);
    bufp->chgBit(oldp+50,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_E));
    bufp->chgCData(oldp+51,(vlSelfRef.Pip_RV32I__DOT__Branch_Cond_E),8);
    bufp->chgBit(oldp+52,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_E));
    bufp->chgCData(oldp+53,(vlSelfRef.Pip_RV32I__DOT__Load_Size_E),2);
    bufp->chgIData(oldp+54,(vlSelfRef.Pip_RV32I__DOT__Read_Data1_E),32);
    bufp->chgIData(oldp+55,(vlSelfRef.Pip_RV32I__DOT__Read_Data2_E),32);
    bufp->chgIData(oldp+56,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_E),32);
    bufp->chgIData(oldp+57,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_E),32);
    bufp->chgIData(oldp+58,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_E),32);
    bufp->chgCData(oldp+59,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_E),5);
    bufp->chgBit(oldp+60,(vlSelfRef.Pip_RV32I__DOT__Branch_Taken_E));
    bufp->chgIData(oldp+61,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_M),32);
    bufp->chgIData(oldp+62,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_M),32);
    bufp->chgIData(oldp+63,(vlSelfRef.Pip_RV32I__DOT__Read_Data2_M),32);
    bufp->chgBit(oldp+64,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_M));
    bufp->chgCData(oldp+65,(vlSelfRef.Pip_RV32I__DOT__Func3_M),2);
    bufp->chgCData(oldp+66,(vlSelfRef.Pip_RV32I__DOT__Result_Src_M),3);
    bufp->chgCData(oldp+67,(vlSelfRef.Pip_RV32I__DOT__Load_Size_M),2);
    bufp->chgBit(oldp+68,(vlSelfRef.Pip_RV32I__DOT__Load_Unsigned_M));
    bufp->chgIData(oldp+69,(vlSelfRef.Pip_RV32I__DOT__Loaded_Data_M),32);
    bufp->chgIData(oldp+70,(vlSelfRef.Pip_RV32I__DOT__DM_WrData_M),32);
    bufp->chgIData(oldp+71,(vlSelfRef.Pip_RV32I__DOT__DM_Addr_M),32);
    bufp->chgBit(oldp+72,(vlSelfRef.Pip_RV32I__DOT__DM_Wr_Req_M));
    bufp->chgCData(oldp+73,(vlSelfRef.Pip_RV32I__DOT__DM_Mask_M),4);
    bufp->chgBit(oldp+74,(vlSelfRef.Pip_RV32I__DOT__DM_WrEn_M));
    bufp->chgIData(oldp+75,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_M),32);
    bufp->chgIData(oldp+76,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_M),32);
    bufp->chgCData(oldp+77,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_M),5);
    bufp->chgIData(oldp+78,(vlSelfRef.Pip_RV32I__DOT__Data_M),32);
    bufp->chgIData(oldp+79,(vlSelfRef.Pip_RV32I__DOT__PC_Plus4_W),32);
    bufp->chgIData(oldp+80,(vlSelfRef.Pip_RV32I__DOT__ALU_Result_W),32);
    bufp->chgIData(oldp+81,(vlSelfRef.Pip_RV32I__DOT__Loaded_Data_W),32);
    bufp->chgIData(oldp+82,(vlSelfRef.Pip_RV32I__DOT__Imm_Ext_W),32);
    bufp->chgIData(oldp+83,(vlSelfRef.Pip_RV32I__DOT__Imm_Added_W),32);
    bufp->chgIData(oldp+84,(vlSelfRef.Pip_RV32I__DOT__Result_W),32);
    bufp->chgBit(oldp+85,(vlSelfRef.Pip_RV32I__DOT__Reg_WrEn_W));
    bufp->chgCData(oldp+86,(vlSelfRef.Pip_RV32I__DOT__Result_Src_W),3);
    bufp->chgCData(oldp+87,(vlSelfRef.Pip_RV32I__DOT__Des_Addr_W),5);
    bufp->chgBit(oldp+88,(vlSelfRef.Pip_RV32I__DOT__Stall_F));
    bufp->chgBit(oldp+89,(vlSelfRef.Pip_RV32I__DOT__Stall_D));
    bufp->chgBit(oldp+90,(vlSelfRef.Pip_RV32I__DOT__Flush_D));
    bufp->chgBit(oldp+91,(vlSelfRef.Pip_RV32I__DOT__Flush_E));
    bufp->chgCData(oldp+92,(vlSelfRef.Pip_RV32I__DOT__ForwardA_E),2);
    bufp->chgCData(oldp+93,(vlSelfRef.Pip_RV32I__DOT__ForwardB_E),2);
    bufp->chgCData(oldp+94,(vlSelfRef.Pip_RV32I__DOT__Src_Addr1_E),5);
    bufp->chgCData(oldp+95,(vlSelfRef.Pip_RV32I__DOT__Src_Addr2_E),5);
    bufp->chgIData(oldp+96,(vlSelfRef.Pip_RV32I__DOT__ForwardA_Data),32);
    bufp->chgIData(oldp+97,(vlSelfRef.Pip_RV32I__DOT__ForwardB_Data),32);
    bufp->chgIData(oldp+98,(vlSelfRef.Pip_RV32I__DOT__SrcA),32);
    bufp->chgIData(oldp+99,(vlSelfRef.Pip_RV32I__DOT__SrcB),32);
    bufp->chgBit(oldp+100,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Iadder_Src_In));
    bufp->chgIData(oldp+101,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__PC_In),32);
    bufp->chgIData(oldp+102,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Src_Data1_In),32);
    bufp->chgIData(oldp+103,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Imm_Data_In),32);
    bufp->chgIData(oldp+104,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__Added_Data_Out),32);
    bufp->chgIData(oldp+105,(vlSelfRef.Pip_RV32I__DOT__Imm_Adder__DOT__temp_adder_src),32);
    bufp->chgIData(oldp+106,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__Src1_In),32);
    bufp->chgIData(oldp+107,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__Src2_In),32);
    bufp->chgCData(oldp+108,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__ALU_Control_In),4);
    bufp->chgIData(oldp+109,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__ALU_Result_Out),32);
    bufp->chgIData(oldp+110,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__signed_src1),32);
    bufp->chgIData(oldp+111,(vlSelfRef.Pip_RV32I__DOT__alu__DOT__signed_src2),32);
    bufp->chgIData(oldp+112,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Src_Data1_In),32);
    bufp->chgIData(oldp+113,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Src_Data2_In),32);
    bufp->chgCData(oldp+114,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal),8);
    bufp->chgBit(oldp+115,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__Branch_Taken_Out));
    bufp->chgBit(oldp+116,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__equal));
    bufp->chgBit(oldp+117,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__not_equal));
    bufp->chgBit(oldp+118,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__less_than));
    bufp->chgBit(oldp+119,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__greater_equal));
    bufp->chgBit(oldp+120,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__less_than_unsigned));
    bufp->chgBit(oldp+121,(vlSelfRef.Pip_RV32I__DOT__branch_unit__DOT__greater_equal_unsigned));
    bufp->chgCData(oldp+122,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Opcode),7);
    bufp->chgCData(oldp+123,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Func3),3);
    bufp->chgBit(oldp+124,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Func7));
    bufp->chgBit(oldp+125,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Reg_WrEn_Out));
    bufp->chgCData(oldp+126,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Imm_Type_Out),3);
    bufp->chgBit(oldp+127,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Iadder_Src_Out));
    bufp->chgBit(oldp+128,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__ALU_Src_Out));
    bufp->chgCData(oldp+129,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__ALU_Control_Out),4);
    bufp->chgBit(oldp+130,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__DM_WrEn_Out));
    bufp->chgCData(oldp+131,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal),8);
    bufp->chgBit(oldp+132,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Load_Unsigned_Out));
    bufp->chgCData(oldp+133,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Load_Size_Out),2);
    bufp->chgCData(oldp+134,(vlSelfRef.Pip_RV32I__DOT__decoder__DOT__Result_Src_Out),3);
    bufp->chgCData(oldp+135,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_D_In),5);
    bufp->chgCData(oldp+136,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_D_In),5);
    bufp->chgCData(oldp+137,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_E_In),5);
    bufp->chgBit(oldp+138,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_E_In));
    bufp->chgCData(oldp+139,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Result_Src_E_In),3);
    bufp->chgCData(oldp+140,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_E_In),5);
    bufp->chgCData(oldp+141,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_E_In),5);
    bufp->chgCData(oldp+142,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_M_In),5);
    bufp->chgBit(oldp+143,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_M_In));
    bufp->chgCData(oldp+144,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_W_In),5);
    bufp->chgBit(oldp+145,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_W_In));
    bufp->chgBit(oldp+146,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Branch_Taken_E_In));
    bufp->chgBit(oldp+147,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Stall_F_Out));
    bufp->chgBit(oldp+148,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Stall_D_Out));
    bufp->chgBit(oldp+149,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Flush_D_Out));
    bufp->chgBit(oldp+150,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__Flush_E_Out));
    bufp->chgCData(oldp+151,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__ForwardA_E_Out),2);
    bufp->chgCData(oldp+152,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__ForwardB_E_Out),2);
    bufp->chgBit(oldp+153,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__load_use_hazard));
    bufp->chgBit(oldp+154,(vlSelfRef.Pip_RV32I__DOT__hazard_unit__DOT__control_hazard));
    bufp->chgIData(oldp+155,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Instr_In),25);
    bufp->chgCData(oldp+156,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Imm_Type_In),3);
    bufp->chgIData(oldp+157,(vlSelfRef.Pip_RV32I__DOT__imm_extend__DOT__Imm_Out),32);
    bufp->chgIData(oldp+158,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Read_Data_In),32);
    bufp->chgCData(oldp+159,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__iadder_out_1to0_in),2);
    bufp->chgCData(oldp+160,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Load_Size_In),2);
    bufp->chgBit(oldp+161,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Load_Unsigned_In));
    bufp->chgIData(oldp+162,(vlSelfRef.Pip_RV32I__DOT__load_unit__DOT__Loaded_Data_Out),32);
    bufp->chgBit(oldp+163,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Clk_In));
    bufp->chgBit(oldp+164,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Rst_In));
    bufp->chgBit(oldp+165,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Stall_In));
    bufp->chgBit(oldp+166,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Branch_Taken_In));
    bufp->chgIData(oldp+167,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Target_PC_In),32);
    bufp->chgIData(oldp+168,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__PC_Out),32);
    bufp->chgIData(oldp+169,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__PC_Plus4_Out),32);
    bufp->chgIData(oldp+170,(vlSelfRef.Pip_RV32I__DOT__pc_unit__DOT__Temp_PC_Out),32);
    bufp->chgBit(oldp+171,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Clk_In));
    bufp->chgBit(oldp+172,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Rst_In));
    bufp->chgBit(oldp+173,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Flush_In));
    bufp->chgBit(oldp+174,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_In));
    bufp->chgCData(oldp+175,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_In),3);
    bufp->chgBit(oldp+176,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_In));
    bufp->chgBit(oldp+177,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_In));
    bufp->chgCData(oldp+178,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_In),2);
    bufp->chgBit(oldp+179,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_In));
    bufp->chgCData(oldp+180,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_In),4);
    bufp->chgBit(oldp+181,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_In));
    bufp->chgIData(oldp+182,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_In),32);
    bufp->chgCData(oldp+183,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Func3_In),2);
    bufp->chgCData(oldp+184,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_In),8);
    bufp->chgIData(oldp+185,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_In),32);
    bufp->chgIData(oldp+186,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_In),32);
    bufp->chgCData(oldp+187,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_In),5);
    bufp->chgCData(oldp+188,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_In),5);
    bufp->chgCData(oldp+189,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_In),5);
    bufp->chgCData(oldp+190,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_Out),5);
    bufp->chgCData(oldp+191,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_Out),5);
    bufp->chgCData(oldp+192,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_Out),5);
    bufp->chgBit(oldp+193,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_Out));
    bufp->chgCData(oldp+194,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_Out),3);
    bufp->chgBit(oldp+195,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_Out));
    bufp->chgBit(oldp+196,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_Out));
    bufp->chgCData(oldp+197,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_Out),2);
    bufp->chgBit(oldp+198,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_Out));
    bufp->chgCData(oldp+199,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_Out),4);
    bufp->chgBit(oldp+200,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_Out));
    bufp->chgIData(oldp+201,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Out),32);
    bufp->chgCData(oldp+202,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Func3_Out),2);
    bufp->chgCData(oldp+203,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_Out),8);
    bufp->chgIData(oldp+204,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_Out),32);
    bufp->chgIData(oldp+205,(vlSelfRef.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_Out),32);
    bufp->chgBit(oldp+206,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Clk_In));
    bufp->chgBit(oldp+207,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Rst_In));
    bufp->chgBit(oldp+208,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_In));
    bufp->chgCData(oldp+209,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_In),3);
    bufp->chgCData(oldp+210,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_In),2);
    bufp->chgBit(oldp+211,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_In));
    bufp->chgBit(oldp+212,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_In));
    bufp->chgCData(oldp+213,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Func3_In),2);
    bufp->chgIData(oldp+214,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_In),32);
    bufp->chgIData(oldp+215,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_In),32);
    bufp->chgIData(oldp+216,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_In),32);
    bufp->chgIData(oldp+217,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_In),32);
    bufp->chgIData(oldp+218,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_In),32);
    bufp->chgCData(oldp+219,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_In),5);
    bufp->chgCData(oldp+220,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_Out),5);
    bufp->chgIData(oldp+221,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_Out),32);
    bufp->chgBit(oldp+222,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_Out));
    bufp->chgCData(oldp+223,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_Out),3);
    bufp->chgCData(oldp+224,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_Out),2);
    bufp->chgBit(oldp+225,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_Out));
    bufp->chgBit(oldp+226,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_Out));
    bufp->chgCData(oldp+227,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Func3_Out),2);
    bufp->chgIData(oldp+228,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_Out),32);
    bufp->chgIData(oldp+229,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_Out),32);
    bufp->chgIData(oldp+230,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_Out),32);
    bufp->chgIData(oldp+231,(vlSelfRef.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_Out),32);
    bufp->chgBit(oldp+232,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Clk_In));
    bufp->chgBit(oldp+233,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Rst_In));
    bufp->chgBit(oldp+234,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Stall_In));
    bufp->chgBit(oldp+235,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Flush_In));
    bufp->chgIData(oldp+236,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Instr_In),32);
    bufp->chgIData(oldp+237,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_In),32);
    bufp->chgIData(oldp+238,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_In),32);
    bufp->chgIData(oldp+239,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__Instr_Out),32);
    bufp->chgIData(oldp+240,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Out),32);
    bufp->chgIData(oldp+241,(vlSelfRef.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_Out),32);
    bufp->chgBit(oldp+242,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Clk_In));
    bufp->chgBit(oldp+243,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Rst_In));
    bufp->chgBit(oldp+244,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__WrEn_In));
    bufp->chgCData(oldp+245,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Addr1_In),5);
    bufp->chgCData(oldp+246,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Addr2_In),5);
    bufp->chgCData(oldp+247,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Des_Addr_In),5);
    bufp->chgIData(oldp+248,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Des_Data_In),32);
    bufp->chgIData(oldp+249,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Data1_Out),32);
    bufp->chgIData(oldp+250,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Src_Data2_Out),32);
    bufp->chgIData(oldp+251,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data1),32);
    bufp->chgIData(oldp+252,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data2),32);
    bufp->chgIData(oldp+253,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[0]),32);
    bufp->chgIData(oldp+254,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[1]),32);
    bufp->chgIData(oldp+255,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[2]),32);
    bufp->chgIData(oldp+256,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[3]),32);
    bufp->chgIData(oldp+257,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[4]),32);
    bufp->chgIData(oldp+258,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[5]),32);
    bufp->chgIData(oldp+259,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[6]),32);
    bufp->chgIData(oldp+260,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[7]),32);
    bufp->chgIData(oldp+261,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[8]),32);
    bufp->chgIData(oldp+262,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[9]),32);
    bufp->chgIData(oldp+263,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[10]),32);
    bufp->chgIData(oldp+264,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[11]),32);
    bufp->chgIData(oldp+265,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[12]),32);
    bufp->chgIData(oldp+266,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[13]),32);
    bufp->chgIData(oldp+267,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[14]),32);
    bufp->chgIData(oldp+268,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[15]),32);
    bufp->chgIData(oldp+269,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[16]),32);
    bufp->chgIData(oldp+270,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[17]),32);
    bufp->chgIData(oldp+271,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[18]),32);
    bufp->chgIData(oldp+272,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[19]),32);
    bufp->chgIData(oldp+273,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[20]),32);
    bufp->chgIData(oldp+274,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[21]),32);
    bufp->chgIData(oldp+275,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[22]),32);
    bufp->chgIData(oldp+276,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[23]),32);
    bufp->chgIData(oldp+277,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[24]),32);
    bufp->chgIData(oldp+278,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[25]),32);
    bufp->chgIData(oldp+279,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[26]),32);
    bufp->chgIData(oldp+280,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[27]),32);
    bufp->chgIData(oldp+281,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[28]),32);
    bufp->chgIData(oldp+282,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[29]),32);
    bufp->chgIData(oldp+283,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[30]),32);
    bufp->chgIData(oldp+284,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__register[31]),32);
    bufp->chgIData(oldp+285,(vlSelfRef.Pip_RV32I__DOT__reg_file__DOT__i),32);
    bufp->chgBit(oldp+286,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Clk_In));
    bufp->chgBit(oldp+287,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Rst_In));
    bufp->chgBit(oldp+288,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_In));
    bufp->chgCData(oldp+289,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_In),3);
    bufp->chgIData(oldp+290,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_In),32);
    bufp->chgIData(oldp+291,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_In),32);
    bufp->chgIData(oldp+292,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_In),32);
    bufp->chgIData(oldp+293,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_In),32);
    bufp->chgIData(oldp+294,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_In),32);
    bufp->chgCData(oldp+295,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_In),5);
    bufp->chgCData(oldp+296,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_Out),5);
    bufp->chgIData(oldp+297,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_Out),32);
    bufp->chgBit(oldp+298,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_Out));
    bufp->chgCData(oldp+299,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_Out),3);
    bufp->chgIData(oldp+300,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_Out),32);
    bufp->chgIData(oldp+301,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_Out),32);
    bufp->chgIData(oldp+302,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_Out),32);
    bufp->chgIData(oldp+303,(vlSelfRef.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_Out),32);
    bufp->chgBit(oldp+304,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_In));
    bufp->chgCData(oldp+305,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Func3_In),2);
    bufp->chgIData(oldp+306,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Added_Data_In),32);
    bufp->chgIData(oldp+307,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__Src_Data2_In),32);
    bufp->chgCData(oldp+308,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrMask_Out),4);
    bufp->chgIData(oldp+309,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrData_Out),32);
    bufp->chgIData(oldp+310,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_Addr_Out),32);
    bufp->chgBit(oldp+311,(vlSelfRef.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_Out));
    bufp->chgCData(oldp+312,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Result_Src_In),3);
    bufp->chgIData(oldp+313,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Imm_Data_In),32);
    bufp->chgIData(oldp+314,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__ALU_Result_In),32);
    bufp->chgIData(oldp+315,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Loaded_Data_In),32);
    bufp->chgIData(oldp+316,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Imm_Added_In),32);
    bufp->chgIData(oldp+317,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__PC_Plus4_In),32);
    bufp->chgIData(oldp+318,(vlSelfRef.Pip_RV32I__DOT__wb_unit__DOT__Result_Out),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
