// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_Pip_RV32I);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__Imm_Adder);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__alu);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__branch_unit);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__decoder);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__hazard_unit);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__imm_extend);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__load_unit);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__pc_unit);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_d_e);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_e_m);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_f_d);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_file);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_m_w);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__store_unit);
    __Vhier.remove(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__wb_unit);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(47);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_Pip_RV32I.configure(this, name(), "Pip_RV32I", "Pip_RV32I", "Pip_RV32I", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__Imm_Adder.configure(this, name(), "Pip_RV32I.Imm_Adder", "Imm_Adder", "Imm_Adder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__alu.configure(this, name(), "Pip_RV32I.alu", "alu", "ALU", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__branch_unit.configure(this, name(), "Pip_RV32I.branch_unit", "branch_unit", "Branch_Predictor", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__decoder.configure(this, name(), "Pip_RV32I.decoder", "decoder", "Decoder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__hazard_unit.configure(this, name(), "Pip_RV32I.hazard_unit", "hazard_unit", "Hazard_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__imm_extend.configure(this, name(), "Pip_RV32I.imm_extend", "imm_extend", "Extend_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__load_unit.configure(this, name(), "Pip_RV32I.load_unit", "load_unit", "Load_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__pc_unit.configure(this, name(), "Pip_RV32I.pc_unit", "pc_unit", "PC_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__reg_d_e.configure(this, name(), "Pip_RV32I.reg_d_e", "reg_d_e", "Reg_D_E", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__reg_e_m.configure(this, name(), "Pip_RV32I.reg_e_m", "reg_e_m", "Reg_E_M", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__reg_f_d.configure(this, name(), "Pip_RV32I.reg_f_d", "reg_f_d", "Reg_F_D", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__reg_file.configure(this, name(), "Pip_RV32I.reg_file", "reg_file", "Register_File", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__reg_m_w.configure(this, name(), "Pip_RV32I.reg_m_w", "reg_m_w", "Reg_M_W", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__store_unit.configure(this, name(), "Pip_RV32I.store_unit", "store_unit", "Store_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_Pip_RV32I__wb_unit.configure(this, name(), "Pip_RV32I.wb_unit", "wb_unit", "WB_Unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_Pip_RV32I);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__Imm_Adder);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__alu);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__branch_unit);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__decoder);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__hazard_unit);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__imm_extend);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__load_unit);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__pc_unit);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_d_e);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_e_m);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_f_d);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_file);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__reg_m_w);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__store_unit);
    __Vhier.add(&__Vscope_Pip_RV32I, &__Vscope_Pip_RV32I__wb_unit);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Control_D", &(TOP.Pip_RV32I__DOT__ALU_Control_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Control_E", &(TOP.Pip_RV32I__DOT__ALU_Control_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Result_E", &(TOP.Pip_RV32I__DOT__ALU_Result_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Result_M", &(TOP.Pip_RV32I__DOT__ALU_Result_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Result_W", &(TOP.Pip_RV32I__DOT__ALU_Result_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Src_D", &(TOP.Pip_RV32I__DOT__ALU_Src_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ALU_Src_E", &(TOP.Pip_RV32I__DOT__ALU_Src_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Branch_Cond_D", &(TOP.Pip_RV32I__DOT__Branch_Cond_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Branch_Cond_E", &(TOP.Pip_RV32I__DOT__Branch_Cond_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Branch_Taken_E", &(TOP.Pip_RV32I__DOT__Branch_Taken_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Addr_M", &(TOP.Pip_RV32I__DOT__DM_Addr_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Addr_Out", &(TOP.Pip_RV32I__DOT__DM_Addr_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Data_In", &(TOP.Pip_RV32I__DOT__DM_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Data_Out", &(TOP.Pip_RV32I__DOT__DM_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Mask_M", &(TOP.Pip_RV32I__DOT__DM_Mask_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Mask_Out", &(TOP.Pip_RV32I__DOT__DM_Mask_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_WrData_M", &(TOP.Pip_RV32I__DOT__DM_WrData_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_WrEn_D", &(TOP.Pip_RV32I__DOT__DM_WrEn_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_WrEn_E", &(TOP.Pip_RV32I__DOT__DM_WrEn_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_WrEn_M", &(TOP.Pip_RV32I__DOT__DM_WrEn_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.Pip_RV32I__DOT__DM_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"DM_Wr_Req_M", &(TOP.Pip_RV32I__DOT__DM_Wr_Req_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Data_M", &(TOP.Pip_RV32I__DOT__Data_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Des_Addr_D", &(TOP.Pip_RV32I__DOT__Des_Addr_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Des_Addr_E", &(TOP.Pip_RV32I__DOT__Des_Addr_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Des_Addr_M", &(TOP.Pip_RV32I__DOT__Des_Addr_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Des_Addr_W", &(TOP.Pip_RV32I__DOT__Des_Addr_W), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Flush_D", &(TOP.Pip_RV32I__DOT__Flush_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Flush_E", &(TOP.Pip_RV32I__DOT__Flush_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ForwardA_Data", &(TOP.Pip_RV32I__DOT__ForwardA_Data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ForwardA_E", &(TOP.Pip_RV32I__DOT__ForwardA_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ForwardB_Data", &(TOP.Pip_RV32I__DOT__ForwardB_Data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"ForwardB_E", &(TOP.Pip_RV32I__DOT__ForwardB_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Func3_D", &(TOP.Pip_RV32I__DOT__Func3_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Func3_E", &(TOP.Pip_RV32I__DOT__Func3_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Func3_M", &(TOP.Pip_RV32I__DOT__Func3_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Func7_D", &(TOP.Pip_RV32I__DOT__Func7_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Iadder_Src_D", &(TOP.Pip_RV32I__DOT__Iadder_Src_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Iadder_Src_E", &(TOP.Pip_RV32I__DOT__Iadder_Src_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Added_E", &(TOP.Pip_RV32I__DOT__Imm_Added_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Added_M", &(TOP.Pip_RV32I__DOT__Imm_Added_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Added_W", &(TOP.Pip_RV32I__DOT__Imm_Added_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Ext_D", &(TOP.Pip_RV32I__DOT__Imm_Ext_D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Ext_E", &(TOP.Pip_RV32I__DOT__Imm_Ext_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Ext_M", &(TOP.Pip_RV32I__DOT__Imm_Ext_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Ext_W", &(TOP.Pip_RV32I__DOT__Imm_Ext_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Imm_Type_D", &(TOP.Pip_RV32I__DOT__Imm_Type_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Immediate_D", &(TOP.Pip_RV32I__DOT__Immediate_D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,24,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Instr_Addr_Out", &(TOP.Pip_RV32I__DOT__Instr_Addr_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Instruction_D", &(TOP.Pip_RV32I__DOT__Instruction_D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Instruction_F", &(TOP.Pip_RV32I__DOT__Instruction_F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Instruction_In", &(TOP.Pip_RV32I__DOT__Instruction_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Size_D", &(TOP.Pip_RV32I__DOT__Load_Size_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Size_E", &(TOP.Pip_RV32I__DOT__Load_Size_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Size_M", &(TOP.Pip_RV32I__DOT__Load_Size_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Unsigned_D", &(TOP.Pip_RV32I__DOT__Load_Unsigned_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Unsigned_E", &(TOP.Pip_RV32I__DOT__Load_Unsigned_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Load_Unsigned_M", &(TOP.Pip_RV32I__DOT__Load_Unsigned_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Loaded_Data_M", &(TOP.Pip_RV32I__DOT__Loaded_Data_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Loaded_Data_W", &(TOP.Pip_RV32I__DOT__Loaded_Data_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Opcode_D", &(TOP.Pip_RV32I__DOT__Opcode_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_D", &(TOP.Pip_RV32I__DOT__PC_D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_E", &(TOP.Pip_RV32I__DOT__PC_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_F", &(TOP.Pip_RV32I__DOT__PC_F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_Plus4_D", &(TOP.Pip_RV32I__DOT__PC_Plus4_D), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_Plus4_E", &(TOP.Pip_RV32I__DOT__PC_Plus4_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_Plus4_F", &(TOP.Pip_RV32I__DOT__PC_Plus4_F), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_Plus4_M", &(TOP.Pip_RV32I__DOT__PC_Plus4_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"PC_Plus4_W", &(TOP.Pip_RV32I__DOT__PC_Plus4_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Read_Data1_E", &(TOP.Pip_RV32I__DOT__Read_Data1_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Read_Data2_E", &(TOP.Pip_RV32I__DOT__Read_Data2_E), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Read_Data2_M", &(TOP.Pip_RV32I__DOT__Read_Data2_M), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Reg_WrEn_D", &(TOP.Pip_RV32I__DOT__Reg_WrEn_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Reg_WrEn_E", &(TOP.Pip_RV32I__DOT__Reg_WrEn_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Reg_WrEn_M", &(TOP.Pip_RV32I__DOT__Reg_WrEn_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Reg_WrEn_W", &(TOP.Pip_RV32I__DOT__Reg_WrEn_W), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Result_Src_D", &(TOP.Pip_RV32I__DOT__Result_Src_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Result_Src_E", &(TOP.Pip_RV32I__DOT__Result_Src_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Result_Src_M", &(TOP.Pip_RV32I__DOT__Result_Src_M), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Result_Src_W", &(TOP.Pip_RV32I__DOT__Result_Src_W), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Result_W", &(TOP.Pip_RV32I__DOT__Result_W), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"SrcA", &(TOP.Pip_RV32I__DOT__SrcA), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"SrcB", &(TOP.Pip_RV32I__DOT__SrcB), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Src_Addr1_D", &(TOP.Pip_RV32I__DOT__Src_Addr1_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Src_Addr1_E", &(TOP.Pip_RV32I__DOT__Src_Addr1_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Src_Addr2_D", &(TOP.Pip_RV32I__DOT__Src_Addr2_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Src_Addr2_E", &(TOP.Pip_RV32I__DOT__Src_Addr2_E), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Stall_D", &(TOP.Pip_RV32I__DOT__Stall_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I.varInsert(__Vfinal,"Stall_F", &(TOP.Pip_RV32I__DOT__Stall_F), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"Added_Data_Out", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__Added_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"Iadder_Src_In", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__Iadder_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"Imm_Data_In", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__Imm_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"PC_In", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__PC_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"Src_Data1_In", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__Src_Data1_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__Imm_Adder.varInsert(__Vfinal,"temp_adder_src", &(TOP.Pip_RV32I__DOT__Imm_Adder__DOT__temp_adder_src), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"ALU_Control_In", &(TOP.Pip_RV32I__DOT__alu__DOT__ALU_Control_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"ALU_Result_Out", &(TOP.Pip_RV32I__DOT__alu__DOT__ALU_Result_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"Src1_In", &(TOP.Pip_RV32I__DOT__alu__DOT__Src1_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"Src2_In", &(TOP.Pip_RV32I__DOT__alu__DOT__Src2_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"signed_src1", &(TOP.Pip_RV32I__DOT__alu__DOT__signed_src1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__alu.varInsert(__Vfinal,"signed_src2", &(TOP.Pip_RV32I__DOT__alu__DOT__signed_src2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"Branch_Taken_Out", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__Branch_Taken_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"Src_Data1_In", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__Src_Data1_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"Src_Data2_In", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__Src_Data2_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"bgeu_bltu_bge_blt_bne_beq_jalr_jal", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"equal", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__equal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"greater_equal", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__greater_equal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"greater_equal_unsigned", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__greater_equal_unsigned), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"less_than", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__less_than), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"less_than_unsigned", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__less_than_unsigned), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__branch_unit.varInsert(__Vfinal,"not_equal", &(TOP.Pip_RV32I__DOT__branch_unit__DOT__not_equal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"ALU_Control_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__ALU_Control_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"ALU_Src_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__ALU_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__DM_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Func3", &(TOP.Pip_RV32I__DOT__decoder__DOT__Func3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Func7", &(TOP.Pip_RV32I__DOT__decoder__DOT__Func7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Iadder_Src_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Iadder_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Imm_Type_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Imm_Type_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Load_Size_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Load_Size_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Load_Unsigned_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Load_Unsigned_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Opcode", &(TOP.Pip_RV32I__DOT__decoder__DOT__Opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Reg_WrEn_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Reg_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"Result_Src_Out", &(TOP.Pip_RV32I__DOT__decoder__DOT__Result_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__decoder.varInsert(__Vfinal,"bgeu_bltu_bge_blt_bne_beq_jalr_jal", &(TOP.Pip_RV32I__DOT__decoder__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Branch_Taken_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Branch_Taken_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Des_Addr_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Des_Addr_M_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_M_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Des_Addr_W_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_W_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Flush_D_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Flush_D_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Flush_E_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Flush_E_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"ForwardA_E_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__ForwardA_E_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"ForwardB_E_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__ForwardB_E_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Reg_WrEn_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Reg_WrEn_M_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_M_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Reg_WrEn_W_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_W_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Result_Src_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Result_Src_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Src_Addr1_D_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_D_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Src_Addr1_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Src_Addr2_D_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_D_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Src_Addr2_E_In", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_E_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Stall_D_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Stall_D_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"Stall_F_Out", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__Stall_F_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"control_hazard", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__control_hazard), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__hazard_unit.varInsert(__Vfinal,"load_use_hazard", &(TOP.Pip_RV32I__DOT__hazard_unit__DOT__load_use_hazard), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__imm_extend.varInsert(__Vfinal,"Imm_Out", &(TOP.Pip_RV32I__DOT__imm_extend__DOT__Imm_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__imm_extend.varInsert(__Vfinal,"Imm_Type_In", &(TOP.Pip_RV32I__DOT__imm_extend__DOT__Imm_Type_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__imm_extend.varInsert(__Vfinal,"Instr_In", &(TOP.Pip_RV32I__DOT__imm_extend__DOT__Instr_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,7);
        __Vscope_Pip_RV32I__load_unit.varInsert(__Vfinal,"Load_Size_In", &(TOP.Pip_RV32I__DOT__load_unit__DOT__Load_Size_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__load_unit.varInsert(__Vfinal,"Load_Unsigned_In", &(TOP.Pip_RV32I__DOT__load_unit__DOT__Load_Unsigned_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__load_unit.varInsert(__Vfinal,"Loaded_Data_Out", &(TOP.Pip_RV32I__DOT__load_unit__DOT__Loaded_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__load_unit.varInsert(__Vfinal,"Read_Data_In", &(TOP.Pip_RV32I__DOT__load_unit__DOT__Read_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__load_unit.varInsert(__Vfinal,"iadder_out_1to0_in", &(TOP.Pip_RV32I__DOT__load_unit__DOT__iadder_out_1to0_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Branch_Taken_In", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Branch_Taken_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"PC_Out", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__PC_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"PC_Plus4_Out", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__PC_Plus4_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Stall_In", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Stall_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Target_PC_In", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Target_PC_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__pc_unit.varInsert(__Vfinal,"Temp_PC_Out", &(TOP.Pip_RV32I__DOT__pc_unit__DOT__Temp_PC_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"ALU_Control_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"ALU_Control_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"ALU_Src_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"ALU_Src_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Branch_Cond_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Branch_Cond_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"DM_WrEn_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Des_Addr_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Des_Addr_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Flush_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Flush_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Func3_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Func3_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Func3_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Func3_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Iadder_Src_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Iadder_Src_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Imm_Ext_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Imm_Ext_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Load_Size_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Load_Size_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Load_Unsigned_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Load_Unsigned_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"PC_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__PC_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"PC_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__PC_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"PC_Plus4_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"PC_Plus4_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Reg_WrEn_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Reg_WrEn_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Result_Src_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Result_Src_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Src_Addr1_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Src_Addr1_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Src_Addr2_In", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_d_e.varInsert(__Vfinal,"Src_Addr2_Out", &(TOP.Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"ALU_Result_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"ALU_Result_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Added_Data_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Added_Data_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"DM_WrEn_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Des_Addr_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Des_Addr_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Func3_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Func3_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Func3_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Func3_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Imm_Ext_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Imm_Ext_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Load_Size_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Load_Size_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Load_Unsigned_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Load_Unsigned_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"PC_Plus4_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"PC_Plus4_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Read_Data2_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Read_Data2_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Reg_WrEn_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Reg_WrEn_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Result_Src_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Result_Src_Out", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_e_m.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__reg_e_m__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Flush_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Flush_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Instr_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Instr_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Instr_Out", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Instr_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"PC_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__PC_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"PC_Out", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__PC_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"PC_Plus4_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"PC_Plus4_Out", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_f_d.varInsert(__Vfinal,"Stall_In", &(TOP.Pip_RV32I__DOT__reg_f_d__DOT__Stall_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Des_Addr_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Des_Addr_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Des_Data_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Des_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Src_Addr1_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Src_Addr1_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Src_Addr2_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Src_Addr2_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Src_Data1_Out", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Src_Data1_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Src_Data2_Out", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Src_Data2_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Temp_Src_Data1", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"Temp_Src_Data2", &(TOP.Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"WrEn_In", &(TOP.Pip_RV32I__DOT__reg_file__DOT__WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"i", &(TOP.Pip_RV32I__DOT__reg_file__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_file.varInsert(__Vfinal,"register", &(TOP.Pip_RV32I__DOT__reg_file__DOT__register), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,31 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"ALU_Result_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"ALU_Result_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Added_Data_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Added_Data_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Clk_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Clk_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Des_Addr_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Des_Addr_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Imm_Ext_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Imm_Ext_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Loaded_Data_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Loaded_Data_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"PC_Plus4_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"PC_Plus4_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Reg_WrEn_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Reg_WrEn_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Result_Src_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Result_Src_Out", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_Pip_RV32I__reg_m_w.varInsert(__Vfinal,"Rst_In", &(TOP.Pip_RV32I__DOT__reg_m_w__DOT__Rst_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"Added_Data_In", &(TOP.Pip_RV32I__DOT__store_unit__DOT__Added_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"DM_Addr_Out", &(TOP.Pip_RV32I__DOT__store_unit__DOT__DM_Addr_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"DM_WrData_Out", &(TOP.Pip_RV32I__DOT__store_unit__DOT__DM_WrData_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"DM_WrEn_In", &(TOP.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"DM_WrMask_Out", &(TOP.Pip_RV32I__DOT__store_unit__DOT__DM_WrMask_Out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"Func3_In", &(TOP.Pip_RV32I__DOT__store_unit__DOT__Func3_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_Pip_RV32I__store_unit.varInsert(__Vfinal,"Src_Data2_In", &(TOP.Pip_RV32I__DOT__store_unit__DOT__Src_Data2_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"ALU_Result_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__ALU_Result_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"Imm_Added_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__Imm_Added_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"Imm_Data_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__Imm_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"Loaded_Data_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__Loaded_Data_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"PC_Plus4_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__PC_Plus4_In), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"Result_Out", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__Result_Out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_Pip_RV32I__wb_unit.varInsert(__Vfinal,"Result_Src_In", &(TOP.Pip_RV32I__DOT__wb_unit__DOT__Result_Src_In), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_TOP.varInsert(__Vfinal,"Clk_In", &(TOP.Clk_In), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"DM_Addr_Out", &(TOP.DM_Addr_Out), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"DM_Data_In", &(TOP.DM_Data_In), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"DM_Data_Out", &(TOP.DM_Data_Out), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"DM_Mask_Out", &(TOP.DM_Mask_Out), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_TOP.varInsert(__Vfinal,"DM_WrEn_Out", &(TOP.DM_WrEn_Out), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"Instr_Addr_Out", &(TOP.Instr_Addr_Out), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"Instruction_In", &(TOP.Instruction_In), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"Rst_In", &(TOP.Rst_In), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
    }
}
