// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(Clk_In,0,0);
        VL_IN8(Rst_In,0,0);
        VL_OUT8(DM_Mask_Out,3,0);
        VL_OUT8(DM_WrEn_Out,0,0);
        CData/*0:0*/ Pip_RV32I__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__Rst_In;
        CData/*3:0*/ Pip_RV32I__DOT__DM_Mask_Out;
        CData/*0:0*/ Pip_RV32I__DOT__DM_WrEn_Out;
        CData/*6:0*/ Pip_RV32I__DOT__Opcode_D;
        CData/*2:0*/ Pip_RV32I__DOT__Func3_D;
        CData/*0:0*/ Pip_RV32I__DOT__Func7_D;
        CData/*4:0*/ Pip_RV32I__DOT__Src_Addr1_D;
        CData/*4:0*/ Pip_RV32I__DOT__Src_Addr2_D;
        CData/*4:0*/ Pip_RV32I__DOT__Des_Addr_D;
        CData/*0:0*/ Pip_RV32I__DOT__Reg_WrEn_D;
        CData/*2:0*/ Pip_RV32I__DOT__Result_Src_D;
        CData/*2:0*/ Pip_RV32I__DOT__Imm_Type_D;
        CData/*0:0*/ Pip_RV32I__DOT__Iadder_Src_D;
        CData/*0:0*/ Pip_RV32I__DOT__ALU_Src_D;
        CData/*3:0*/ Pip_RV32I__DOT__ALU_Control_D;
        CData/*0:0*/ Pip_RV32I__DOT__DM_WrEn_D;
        CData/*7:0*/ Pip_RV32I__DOT__Branch_Cond_D;
        CData/*0:0*/ Pip_RV32I__DOT__Load_Unsigned_D;
        CData/*1:0*/ Pip_RV32I__DOT__Load_Size_D;
        CData/*1:0*/ Pip_RV32I__DOT__Func3_E;
        CData/*0:0*/ Pip_RV32I__DOT__Reg_WrEn_E;
        CData/*2:0*/ Pip_RV32I__DOT__Result_Src_E;
        CData/*0:0*/ Pip_RV32I__DOT__Iadder_Src_E;
        CData/*0:0*/ Pip_RV32I__DOT__ALU_Src_E;
        CData/*3:0*/ Pip_RV32I__DOT__ALU_Control_E;
        CData/*0:0*/ Pip_RV32I__DOT__DM_WrEn_E;
        CData/*7:0*/ Pip_RV32I__DOT__Branch_Cond_E;
        CData/*0:0*/ Pip_RV32I__DOT__Load_Unsigned_E;
        CData/*1:0*/ Pip_RV32I__DOT__Load_Size_E;
        CData/*4:0*/ Pip_RV32I__DOT__Des_Addr_E;
        CData/*0:0*/ Pip_RV32I__DOT__Branch_Taken_E;
        CData/*0:0*/ Pip_RV32I__DOT__Reg_WrEn_M;
        CData/*1:0*/ Pip_RV32I__DOT__Func3_M;
        CData/*2:0*/ Pip_RV32I__DOT__Result_Src_M;
        CData/*1:0*/ Pip_RV32I__DOT__Load_Size_M;
        CData/*0:0*/ Pip_RV32I__DOT__Load_Unsigned_M;
        CData/*0:0*/ Pip_RV32I__DOT__DM_Wr_Req_M;
        CData/*3:0*/ Pip_RV32I__DOT__DM_Mask_M;
        CData/*0:0*/ Pip_RV32I__DOT__DM_WrEn_M;
        CData/*4:0*/ Pip_RV32I__DOT__Des_Addr_M;
        CData/*0:0*/ Pip_RV32I__DOT__Reg_WrEn_W;
        CData/*2:0*/ Pip_RV32I__DOT__Result_Src_W;
        CData/*4:0*/ Pip_RV32I__DOT__Des_Addr_W;
        CData/*0:0*/ Pip_RV32I__DOT__Stall_F;
        CData/*0:0*/ Pip_RV32I__DOT__Stall_D;
        CData/*0:0*/ Pip_RV32I__DOT__Flush_D;
        CData/*0:0*/ Pip_RV32I__DOT__Flush_E;
        CData/*1:0*/ Pip_RV32I__DOT__ForwardA_E;
        CData/*1:0*/ Pip_RV32I__DOT__ForwardB_E;
        CData/*4:0*/ Pip_RV32I__DOT__Src_Addr1_E;
        CData/*4:0*/ Pip_RV32I__DOT__Src_Addr2_E;
        CData/*0:0*/ Pip_RV32I__DOT__pc_unit__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__pc_unit__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__pc_unit__DOT__Stall_In;
        CData/*0:0*/ Pip_RV32I__DOT__pc_unit__DOT__Branch_Taken_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Stall_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Flush_In;
    };
    struct {
        CData/*6:0*/ Pip_RV32I__DOT__decoder__DOT__Opcode;
        CData/*2:0*/ Pip_RV32I__DOT__decoder__DOT__Func3;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__Func7;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__Reg_WrEn_Out;
        CData/*2:0*/ Pip_RV32I__DOT__decoder__DOT__Imm_Type_Out;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__Iadder_Src_Out;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__ALU_Src_Out;
        CData/*3:0*/ Pip_RV32I__DOT__decoder__DOT__ALU_Control_Out;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__DM_WrEn_Out;
        CData/*7:0*/ Pip_RV32I__DOT__decoder__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal;
        CData/*0:0*/ Pip_RV32I__DOT__decoder__DOT__Load_Unsigned_Out;
        CData/*1:0*/ Pip_RV32I__DOT__decoder__DOT__Load_Size_Out;
        CData/*2:0*/ Pip_RV32I__DOT__decoder__DOT__Result_Src_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_file__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_file__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_file__DOT__WrEn_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_file__DOT__Src_Addr1_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_file__DOT__Src_Addr2_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_file__DOT__Des_Addr_In;
        CData/*2:0*/ Pip_RV32I__DOT__imm_extend__DOT__Imm_Type_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Flush_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_In;
        CData/*2:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_In;
        CData/*1:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_In;
        CData/*3:0*/ Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_In;
        CData/*1:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Func3_In;
        CData/*7:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr1_Out;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Src_Addr2_Out;
        CData/*4:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Des_Addr_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Reg_WrEn_Out;
        CData/*2:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Result_Src_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__DM_WrEn_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Iadder_Src_Out;
        CData/*1:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Load_Size_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Load_Unsigned_Out;
        CData/*3:0*/ Pip_RV32I__DOT__reg_d_e__DOT__ALU_Control_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_d_e__DOT__ALU_Src_Out;
        CData/*1:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Func3_Out;
        CData/*7:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Branch_Cond_Out;
        CData/*3:0*/ Pip_RV32I__DOT__alu__DOT__ALU_Control_In;
        CData/*0:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__Iadder_Src_In;
        CData/*7:0*/ Pip_RV32I__DOT__branch_unit__DOT__bgeu_bltu_bge_blt_bne_beq_jalr_jal;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__Branch_Taken_Out;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__equal;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__not_equal;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__less_than;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__greater_equal;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__less_than_unsigned;
        CData/*0:0*/ Pip_RV32I__DOT__branch_unit__DOT__greater_equal_unsigned;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_In;
        CData/*2:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_In;
        CData/*1:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_In;
    };
    struct {
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_In;
        CData/*1:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Func3_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Des_Addr_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Reg_WrEn_Out;
        CData/*2:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Result_Src_Out;
        CData/*1:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Load_Size_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Load_Unsigned_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_e_m__DOT__DM_WrEn_Out;
        CData/*1:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Func3_Out;
        CData/*0:0*/ Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_In;
        CData/*1:0*/ Pip_RV32I__DOT__store_unit__DOT__Func3_In;
        CData/*3:0*/ Pip_RV32I__DOT__store_unit__DOT__DM_WrMask_Out;
        CData/*0:0*/ Pip_RV32I__DOT__store_unit__DOT__DM_WrEn_Out;
        CData/*1:0*/ Pip_RV32I__DOT__load_unit__DOT__iadder_out_1to0_in;
        CData/*1:0*/ Pip_RV32I__DOT__load_unit__DOT__Load_Size_In;
        CData/*0:0*/ Pip_RV32I__DOT__load_unit__DOT__Load_Unsigned_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Clk_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Rst_In;
        CData/*0:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_In;
        CData/*2:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_In;
        CData/*4:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Des_Addr_Out;
        CData/*0:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Reg_WrEn_Out;
        CData/*2:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Result_Src_Out;
        CData/*2:0*/ Pip_RV32I__DOT__wb_unit__DOT__Result_Src_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_D_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_D_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_E_In;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_E_In;
        CData/*2:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Result_Src_E_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr1_E_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Src_Addr2_E_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_M_In;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_M_In;
        CData/*4:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Des_Addr_W_In;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Reg_WrEn_W_In;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Branch_Taken_E_In;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Stall_F_Out;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Stall_D_Out;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Flush_D_Out;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__Flush_E_Out;
        CData/*1:0*/ Pip_RV32I__DOT__hazard_unit__DOT__ForwardA_E_Out;
        CData/*1:0*/ Pip_RV32I__DOT__hazard_unit__DOT__ForwardB_E_Out;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__load_use_hazard;
        CData/*0:0*/ Pip_RV32I__DOT__hazard_unit__DOT__control_hazard;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__Clk_In__0;
        CData/*0:0*/ __VactContinue;
        VL_IN(Instruction_In,31,0);
        VL_OUT(Instr_Addr_Out,31,0);
        VL_IN(DM_Data_In,31,0);
        VL_OUT(DM_Addr_Out,31,0);
        VL_OUT(DM_Data_Out,31,0);
        IData/*31:0*/ Pip_RV32I__DOT__Instruction_In;
        IData/*31:0*/ Pip_RV32I__DOT__Instr_Addr_Out;
        IData/*31:0*/ Pip_RV32I__DOT__DM_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__DM_Addr_Out;
        IData/*31:0*/ Pip_RV32I__DOT__DM_Data_Out;
        IData/*31:0*/ Pip_RV32I__DOT__PC_F;
        IData/*31:0*/ Pip_RV32I__DOT__PC_Plus4_F;
        IData/*31:0*/ Pip_RV32I__DOT__Instruction_F;
    };
    struct {
        IData/*31:0*/ Pip_RV32I__DOT__PC_D;
        IData/*31:0*/ Pip_RV32I__DOT__PC_Plus4_D;
        IData/*31:0*/ Pip_RV32I__DOT__Instruction_D;
        IData/*24:0*/ Pip_RV32I__DOT__Immediate_D;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Ext_D;
        IData/*31:0*/ Pip_RV32I__DOT__PC_E;
        IData/*31:0*/ Pip_RV32I__DOT__PC_Plus4_E;
        IData/*31:0*/ Pip_RV32I__DOT__Read_Data1_E;
        IData/*31:0*/ Pip_RV32I__DOT__Read_Data2_E;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Ext_E;
        IData/*31:0*/ Pip_RV32I__DOT__ALU_Result_E;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Added_E;
        IData/*31:0*/ Pip_RV32I__DOT__PC_Plus4_M;
        IData/*31:0*/ Pip_RV32I__DOT__ALU_Result_M;
        IData/*31:0*/ Pip_RV32I__DOT__Read_Data2_M;
        IData/*31:0*/ Pip_RV32I__DOT__Loaded_Data_M;
        IData/*31:0*/ Pip_RV32I__DOT__DM_WrData_M;
        IData/*31:0*/ Pip_RV32I__DOT__DM_Addr_M;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Ext_M;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Added_M;
        IData/*31:0*/ Pip_RV32I__DOT__Data_M;
        IData/*31:0*/ Pip_RV32I__DOT__PC_Plus4_W;
        IData/*31:0*/ Pip_RV32I__DOT__ALU_Result_W;
        IData/*31:0*/ Pip_RV32I__DOT__Loaded_Data_W;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Ext_W;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Added_W;
        IData/*31:0*/ Pip_RV32I__DOT__Result_W;
        IData/*31:0*/ Pip_RV32I__DOT__ForwardA_Data;
        IData/*31:0*/ Pip_RV32I__DOT__ForwardB_Data;
        IData/*31:0*/ Pip_RV32I__DOT__SrcA;
        IData/*31:0*/ Pip_RV32I__DOT__SrcB;
        IData/*31:0*/ Pip_RV32I__DOT__pc_unit__DOT__Target_PC_In;
        IData/*31:0*/ Pip_RV32I__DOT__pc_unit__DOT__PC_Out;
        IData/*31:0*/ Pip_RV32I__DOT__pc_unit__DOT__PC_Plus4_Out;
        IData/*31:0*/ Pip_RV32I__DOT__pc_unit__DOT__Temp_PC_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Instr_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__PC_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__Instr_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__PC_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_f_d__DOT__PC_Plus4_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__Des_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__Src_Data1_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__Src_Data2_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data1;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__Temp_Src_Data2;
        IData/*31:0*/ Pip_RV32I__DOT__reg_file__DOT__i;
        IData/*24:0*/ Pip_RV32I__DOT__imm_extend__DOT__Instr_In;
        IData/*31:0*/ Pip_RV32I__DOT__imm_extend__DOT__Imm_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__PC_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__PC_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__Imm_Ext_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_d_e__DOT__PC_Plus4_Out;
        IData/*31:0*/ Pip_RV32I__DOT__alu__DOT__Src1_In;
        IData/*31:0*/ Pip_RV32I__DOT__alu__DOT__Src2_In;
        IData/*31:0*/ Pip_RV32I__DOT__alu__DOT__ALU_Result_Out;
        IData/*31:0*/ Pip_RV32I__DOT__alu__DOT__signed_src1;
        IData/*31:0*/ Pip_RV32I__DOT__alu__DOT__signed_src2;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__PC_In;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__Src_Data1_In;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__Imm_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__Added_Data_Out;
    };
    struct {
        IData/*31:0*/ Pip_RV32I__DOT__Imm_Adder__DOT__temp_adder_src;
        IData/*31:0*/ Pip_RV32I__DOT__branch_unit__DOT__Src_Data1_In;
        IData/*31:0*/ Pip_RV32I__DOT__branch_unit__DOT__Src_Data2_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Imm_Ext_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__ALU_Result_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Read_Data2_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__Added_Data_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_e_m__DOT__PC_Plus4_Out;
        IData/*31:0*/ Pip_RV32I__DOT__store_unit__DOT__Added_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__store_unit__DOT__Src_Data2_In;
        IData/*31:0*/ Pip_RV32I__DOT__store_unit__DOT__DM_WrData_Out;
        IData/*31:0*/ Pip_RV32I__DOT__store_unit__DOT__DM_Addr_Out;
        IData/*31:0*/ Pip_RV32I__DOT__load_unit__DOT__Read_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__load_unit__DOT__Loaded_Data_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_In;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Imm_Ext_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__ALU_Result_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Loaded_Data_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__Added_Data_Out;
        IData/*31:0*/ Pip_RV32I__DOT__reg_m_w__DOT__PC_Plus4_Out;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__Imm_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__ALU_Result_In;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__Loaded_Data_In;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__Imm_Added_In;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__PC_Plus4_In;
        IData/*31:0*/ Pip_RV32I__DOT__wb_unit__DOT__Result_Out;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 32> Pip_RV32I__DOT__reg_file__DOT__register;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
